docs_dir: docs/book
site_dir: docs/html
pages:
    - Home: index.md
    - Reference:
        - "Session Config": config.md
        - "Session Container": container.md
        - "Session Manager": manager.md
        - "Session Save Handlers": save-handler.md
        - "Session Storage": storage.md
        - "Session Validators": validator.md
site_name: zend-session
site_description: 'Object-oriented interface to PHP sessions and storage.'
repo_url: 'https://github.com/zendframework/zend-session'
